name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ec2-user
          rm -rf ec2-docker-web-app
          git clone https://github.com/yash261405/ec2-docker-web-app.git
          cd ec2-docker-web-app
          sudo systemctl stop nginx || true
          docker build -t yash-app .
          docker stop $(docker ps -q) || true
          docker rm $(docker ps -aq) || true
          docker run -d -p 80:80 yash-app
