script: |
  cd /home/ec2-user
  rm -rf ec2-docker-web-app
  git clone https://github.com/yash261405/ec2-docker-web-app.git
  cd ec2-docker-web-app
  sudo systemctl stop nginx || true
  docker build -t yash-app .
  docker stop $(docker ps -q) || true
  docker rm $(docker ps -aq) || true
  docker run -d -p 80:80 yash-appname: Deploy to EC2


